#!node
const numshift = require("./numshift").numshift;

exports.caesar = function(text, shift) {
    shift = Number(shift);

    if (shift === NaN) {
        throw "shift is not a number";
    }

    let ciphertext = "";

    for (const char of process.argv[2]) {
        ciphertext += numshift(char, process.argv[3]);
    }

    return ciphertext;
}

if (require.main === module) {
    if (process.argv.length < 4) {
        throw `need 2 arguments instead of ${process.argv.length - 2}`;
    }

    console.log(exports.caesar(process.argv[2], process.argv[3]));
}

