#!node
exports.validate = function(char) {
    if (typeof char == "string") {
        checkCharLength(char);

        char = char.charCodeAt();
    }

    return char >= 65 && char <= 90 || char >= 97 && char <= 122;
}

exports.numshift = function(char, shift) {
    checkCharLength(char);

    shift = Number(shift);

    if (shift === NaN) {
        throw "shift is not a number";
    }

    const original = char.charCodeAt();
    let start;

    if (original >= 65 && original <= 90) {
        start = 65;
    } else if (original >= 97 && original <= 122) {
        start = 97;
    } else {
        return char;
    }

    let noo = original + shift;

    if (noo >= start + 26) {
        noo -= 26;
    }

    return String.fromCharCode(noo);
}

function checkCharLength(char) {
    if (char.length != 1) {
        throw `length of "char" argument "${char}" is not 1`;
    }
}

if (require.main === module) {
    console.log(exports.numshift(process.argv[2], process.argv[3]));
}

