#!/bin/bash
original=$(printf "%d" \'$1)

if (( original >= 65 )) && (( original <= 90 ))
then
    start=65
elif (( original >= 97 )) && (( original <= 122 ))
then
    start=97
else
    echo $1

    exit
fi

let new="$original + $2"

if (( new >= start + 26 ))
then
    let "new -= 26"
fi

printf "\x$(printf %x $new)"

