#!node
const charshift = require("./charshift").charshift;
const validate = require("./numshift").validate;

exports.vigenere = function(text, key) {
    let ciphertext = "";
    let j = 0;

    for (const char of text) {
        ciphertext += charshift(char, key[j]);

        if (validate(char)) {
            j = (j + 1) % key.length;
        }
    }

    return ciphertext;
}

if (require.main === module) {
    if (process.argv.length < 4) {
        throw `need 2 arguments instead of ${process.argv.length - 2}`;
    }

    console.log(exports.vigenere(process.argv[2], process.argv[3]));
}

