#!/bin/bash
j=0

for ((i = 0; i < ${#1}; i++))
do
    ciphertext+=$($(dirname "${0}")/charshift "${1:i:1}" "${2:j:1}")

    if [[ $? == 0 ]]
    then
        let "j++"

        echo yes

        if (( j == ${#2} ))
        then
            j=0
        fi
    fi
done

echo "${ciphertext}"
